name: Report incident
description: Report any issues encountered while using the Data Platform tools available like Jira, Github, repositories, etc.
title: "[Incident]: TYPE TITLE HERE"
labels: ["[type] incident"]

body:

  # Data component type
  - type: dropdown
    id: tool
    attributes:
      label: Which tool is the issue related with?
      options:
        - Tool 1
        - Tool 2
        - Tool 3
        - Other
    validations:
      required: true

  # Criticality
  - type: dropdown
    id: criticality
    attributes:
      label: How critical is your incident
      options:
        - Blocking
        - High
        - Medium
        - Low
    validations:
      required: true

  # Goal description
  - type: textarea
    id: incident-description
    attributes:
      label: Description
      description: Please describe as precisely as possible what's the incident. Please attach useful screenshots, even from Browser console if it applies.
      placeholder: I not able to access to _____ from ____
    validations:
      required: true