name: Request new member
description: Request the onboard of a new member/s to the project
title: "[Onboarding]: TYPE TITLE HERE"
labels: ["[type] onboarding"]

body:

  # Final team destination
  - type: dropdown
    id: destination
    attributes:
      label: What team are the new member/s going to be part of?
      options:
        - Team A
        - Team B
        - Team C
        - Other
    validations:
      required: true

  # Start date
  - type: input
    id: date
    attributes:
      label: In what month are the new members joining the team?
    validations:
      required: true

  # Members description
  - type: textarea
    id: members-description
    attributes:
      label: List the new member/s
      description: Please write the details to onboard the new member
      placeholder: Full name - corporate id - Profile (Front developer, Tech lead, Data engineer...)
    validations:
      required: true