name: Request resource
description: Request new resources like repositories, jira boards, new branches, etc.
title: "[Resource]: TYPE TITLE HERE"
labels: ["[type] resource"]

body:

  # Data component type
  - type: dropdown
    id: tool
    attributes:
      label: Which tool is the issue related with?
      options:
        - Tool 1
        - Tool 2
        - Tool 3
        - Others
    validations:
      required: true

  # Criticality
  - type: dropdown
    id: criticality
    attributes:
      label: How critical is the resource you need
      options:
        - Blocking
        - High
        - Medium
        - Low
    validations:
      required: true

  # Goal description
  - type: textarea
    id: resource-description
    attributes:
      label: Resource description
      description: Please describe as precisely as possible what's the resource that you need.
    validations:
      required: true