name: Delete all labels
on: workflow_dispatch

jobs:
  delete-labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Get current labels
        id: get-labels
        uses: actions/github-script@v7
        with:
          script: |
            const labels = await github.rest.issues.listLabelsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            console.log(JSON.stringify(labels.data)); // Print labels data to the console
            console.log(`::set-output name=labels::${JSON.stringify(labels.data)}`); // Set labels as output
        
      - name: Print labels
        run: |
          echo "${{ steps.get-labels.outputs.labels }}"
