name: Delete all labels
on: workflow_dispatch

jobs:
  delete-labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    outputs:
      labels: ${{ steps.get-labels.outputs.labels }}
    steps:
    - name: Get current labels
      id: get-labels
      uses: actions/github-script@v7
      with:
        script: |
          const labels = await github.rest.issues.listLabelsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          console.log(labels.data);  // Add this line to print the labels data
          echo "LABELS=labels.data" >> $GITHUB_ENV
        
    - name: Print labels
      run:
        echo $LABELS
