name: Delete all labels
on: workflow_dispatch

jobs:
  delete-labels:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      issues: write
    steps:
      - name: Get current labels
        id: get-labels
        uses: actions/github-script@v7
        with:
          script: |
            const labels = await github.rest.issues.listLabelsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            return labels.data
        
      - name: Print labels
        run: |
          echo "${{steps.get-labels.outputs.result}}"
          echo "${{steps.get-labels.outputs.result.length}}"

      - name: Delete labels
        if: ${{steps.get-labels.outputs.result.length}} > 0
        run: |
          const labels = ${{steps.get-labels.outputs.result}};
          for (const label of labels) {
            echo label.name
          }
